# Stages (ie phases) that can be used by jobs
stages:
  - init
  - build
  - test
  - plan
  - deploy
  - cleanup

include:
  - project: aop/addons/devops/ci-modules
    file:
      - /templates/AOP-Addons/Default.yml
    ref: main
    rules:
      - if: '$CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_BRANCH !~ /^\d+\.\d+$/ && $CI_COMMIT_TAG == null'

.global-env:
  image: axelor/app-builder:6.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  NODE_OPTIONS: "--max_old_space_size=2048"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Add wrapper and caches folders in cache
.global_cache: &global_cache
  paths:
    - .gradle
    - build
  policy: pull-push

.global_cache_pull: &global_cache_pull
  <<: *global_cache
  policy: pull

# Build artifacts
build:
  extends: .global-env
  stage: build
  cache:
    - *global_cache
  allow_failure: false
  script:
    - ./gradlew -xtest -xspotlessApply -xlicenseFormat clean build
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule" && ($CI_COMMIT_BRANCH =~ /^\d+\.\d+$/ || $CI_COMMIT_TAG)'

# Check code formatting
spotless:
  extends: .global-env
  stage: test
  cache:
    - *global_cache_pull
  allow_failure: true
  script:
    - ./gradlew spotlessCheck
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'

.publish_template: &publish_configuration
  stage: plan
  cache:
    - *global_cache_pull
  script:
    - ./gradlew -xtest -xspotlessApply -xlicenseFormat clean build publish -PaddonsMavenUsername=${NEXUS_ADDONS_DEPLOYMENT_USER} -PaddonsMavenPassword=${NEXUS_ADDONS_DEPLOYMENT_PASSWORD} -P${PUBLISH_TYPE}

publish snapshot:
  <<: *publish_configuration
  variables:
    PUBLISH_TYPE: "snapshotRelease"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /next-.+/)'

publish release:
  <<: *publish_configuration
  variables:
    PUBLISH_TYPE: "finalRelease"
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'

create release:
  stage: plan
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  cache:
    - *global_cache_pull
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
  script:
    - echo "create release for $CI_COMMIT_TAG"
    - |
      RELEASE_DESCRIPTION=$(sed -n "/^## ${CI_COMMIT_TAG}/,/^## /p" CHANGELOG.md | sed '$d;$d')
      release-cli create --name "$CI_COMMIT_TAG" --description "$RELEASE_DESCRIPTION" --tag-name "$CI_COMMIT_TAG" --ref "$CI_COMMIT_TAG"
